CREATE TABLE upshare_user (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE,
    email VARCHAR2(100) UNIQUE,
    image VARCHAR2(100),
    password_hash VARCHAR2(255),
    oauth_provider VARCHAR2(50),
    oauth_user_id VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active NUMBER(1) DEFAULT 1
);

CREATE TABLE upshare_folder (
    folder_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    folder_name VARCHAR2(255) NOT NULL,
    is_favorite NUMBER(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE upshare_file (
    file_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder_id NUMBER NULL,
    user_id NUMBER NOT NULL,
    file_name VARCHAR2(255) NOT NULL,
    file_type VARCHAR(100),
    file_extension VARCHAR2(20),
    file_size NUMBER,
    file_data BLOB NOT NULL,
    is_favorite NUMBER(1) DEFAULT 0,
    is_share NUMBER(1) DEFAULT 0,
    share_code VARCHAR2(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE upshare_folder_relation (
    relation_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder_id NUMBER NOT NULL,
    child_folder_id NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);